name: Github action demo
on: [push]
jobs:
       Explore-GitHub-Action:
        runs-on: ubuntu-latest
        steps:
            - run: echo "the job automaticaly trigged"
            - name: Check
              uses: actions
            - run: echo "${{github.repository}}" represent
            - name: Check
              run:  ls ${{github.workspace}}
            - run: echo "this job's status is ${{job.status}}"