name: Github action dem testing
on:
    schedule:
        - cron: "* * * * *"
jobs:
    report:
       runs-on: ubuntu-latest
       steps:
        - name: Creates file config
          run: touch file.txt
        - name: Commit database
          run: |
           git config --global user.name mostafasadeghifar
           git config --global user.email msadeghifar1996@gmail.com
           git add .
           git commit -am "file changed"
           git push
