name:
    First Cron Jobs
   
    # Controls when the workflow will run
on:
    # Triggers the workflow every 5 minutes
    schedule:
      - cron: "*/5 * * * *"

   
        # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "cron"
    crons:

      # The type of runner that the job will run on
      runs-on: ubuntu-latest
   
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v2
          with:
            php-version: '7.4'
        - name: Run PHP code
          shell: php {0}
          run: |
              <?php
              $welcome = "Hello, world";
              echo $welcome;

        # Runs a single command using the runners shell
        - name: Run a one-line script
           
          run: echo Hello, world!